config/routes.rb
Stocktaking::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :inventories, only: [:create, :destroy, :update, :index, :show] do
    resources :elements, only: [:create, :destroy, :update, :show] do
      resources :loans, only: [:create, :update]
    end
  end

  get "loans/loaned_elements_to_me", to: "loans#loaned_elements_to_me", as: :loaned_elements_to_me
  get "loans/loaned_elements_by_me", to: "loans#loaned_elements_by_me", as: :loaned_elements_by_me

  put "inventories/:id/finish_inventory", to: "inventories#finish_inventory", as: :finish_inventory

  put "loans/:id/finish_loan", to: "loans#finish_loan", as: :finish_loan

  root :to => "home#index"

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  attr_accessible :details, :site, :user_id, :finished
  validates_presence_of :details, :site, :user
  belongs_to :user
  has_many :elements, dependent: :destroy

  scope :finished, where(["finished = ?", true])
  scope :unfinished, where(["finished = ?", false])

end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @inventory = Inventory.new(params[:inventory])
    @inventory.user = current_user
    respond_to do |format|
      if @inventory.save
        flash[:notice] = "El inventario se ha creado correctamente."
      else
        flash[:alert] = "No se pudo crear el inventario."
      end
      format.js
    end
  end

  def index
    @inventories = current_user.inventories.order("created_at DESC")
    @inventory = Inventory.new()
    $path = request.fullpath
  end

  def show
    @inventory = Inventory.find(params[:id])
    $path = request.fullpath
    @elements = Element.where(:inventory_id => @inventory).page(params[:page]).per(10)
  end

  def update
    @inventory = Inventory.find(params[:id])
    unless @inventory.finished?
      respond_to do |format|
        if @inventory.update_attributes(params[:inventory])
          flash[:notice] = "El inventario se ha actualizado correctamente."
        else
          flash[:alert] = "No se pudo actualizar el inventario."
        end
        format.js
      end
    else
      flash[:alert] = "El inventario ya se ha finalizado, no se puede editar."
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    unless @inventory.finished?
      if @inventory.destroy
        flash[:notice] = "Se ha destruido el inventario correctamente."
        redirect_to inventories_path
      else
        flash[:alert] = "No se ha podido eliminar el inventario."
        redirect_to inventories_path
      end
    else
      flash[:alert] = "El inventario ya se ha finalizado, no se puede eliminar."
      redirect_to inventories_path
    end
  end

  def finish_inventory
    @inventory = Inventory.find(params[:id])
    @inventory.finished = true
    if @inventory.save
      flash[:notice] = "Usted ha terminado de editar el inventario: #{@inventory.site}"
      redirect_to inventories_path
    else
      flash[:alert] = "No se ha podido eliminar el inventario."
    end
  end

end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventories/_form.html.erb
<div id="modalInventory" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalInventoryLabel" aria-hidden="true">
  <div class="modal-header" style="height: 44px;">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <%if $path == "/inventories"%>
      <h3 id="modalInventoryLabel">Crear Inventario</h3>
    <%else%>
      <h3 id="modalInventoryLabel">Editar Inventario</h3>
    <%end%>
    <hr>
  </div>
  <div id="errors" class="hide errors" style = "float: right"></div>
  <%= simple_form_for([@inventory], remote: :true, html: {style: "margin-bottom: 0px"}) do |f|%>
    <div class="modal-body">
      <%= f.input :site, label: "Lugar de ubicación" %>
      <%= f.input :details, :input_html =>{:rows => 3}, label: "Detalles"%>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <%= f.button :submit , 'Aceptar', class: "btn btn-primary" %>
    </div>
  <%end%>
</div>

app/views/inventories/create.js.erb
<% if @inventory.errors.messages.blank? %>
  location.href = '<%= inventory_path(@inventory) %>'
<% else %>
  <%
  error = '<ul>'
  @inventory.errors.messages.each do |msg|
    error += "<li>#{I18n.t(msg[0])} #{msg[1].first}</li>"
  end
  error += "</ul>"
  %>
  $('div#errors').html('<%= error.html_safe %>').show();
<% end %>

app/views/inventories/index.html.erb
<%= title "Inventarios - Stocktaking" %>
<fieldset>
  <legend>Inventarios <a href="#modalInventory" role="button" class="btn btn-success btn-mini" data-toggle="modal"><i class="icon-plus-sign" rel= "tooltip" title= "Crear Inventario"></i></a> </legend>

	<div class = "form_inventory">
		<%if @inventories.size > 0 %>
			<div class="accordion" id="accordion1">
			  <%@inventories.each do |inventory| %>
				  <div class="accordion-group">
				    <div class="accordion-heading">
				      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href= <%="#collapse#{inventory.id}"%> >
				        <%=inventory.site%>
				      </a>
				    </div>
				    <div id= "<%="collapse#{inventory.id}"%>" class="accordion-body collapse in">
				      <div class="accordion-inner">
				        <strong> Descripción: </strong>
				        <p><%=inventory.details %></p>
				        <p><strong> Finalizado: </strong><%= inventory.finished ? "Sí" : "No" %></p>
				        <%=link_to(content_tag(:span, content_tag(:i, nil, :class => "icon-eye-open")), inventory_path(inventory), class: "btn btn-mini", :rel => "tooltip", :"title" => "Ir a Inventario")%>
								<% if inventory.finished == false%>
									<a href="#modalEdit<%="#{inventory.id}"%>" role="button" class="btn btn-mini" data-toggle="modal"><i class="icon-edit" rel= "tooltip" title= "Editar Inventario"></i></a>
									<%=link_to(content_tag(:span, content_tag(:i, nil, :class => "icon-trash")), inventory_path(inventory), method: :delete, data:{confirm: "¿Realmente deseas elminiar este inventario?"}, class: "btn btn-mini", :rel => "tooltip", :"title" => "Eliminar Inventario")%>
								<%end%>
				      </div>
			    	</div>
					  <div id="modalEdit<%="#{inventory.id}"%>" class="modal hide fade ui-state-disabled" tabindex="-1" role="dialog" aria-labelledby="modalEditLabel" aria-hidden="true">
						  <div class="modal-header" style="height: 44px;">
						    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						    <h3 id="modalEditLabel">Editar Inventario</h3>
						    <hr>
						  </div>
						  <div id="errors_edit_<%=inventory.id%>" class="hide errors" style = "float: right"></div>
						  <%= simple_form_for([inventory], remote: :true, html: {style: "margin-bottom: 0px"}) do |f|%>
						    <div class="modal-body">
						      <%= f.input :site, label: "Lugar de ubicación" %>
						      <%= f.input :details, :input_html =>{:rows => 10}, label: "Detalles"%>
						    </div>
						    <div class="modal-footer">
						      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						      <%= f.button :submit , 'Aceptar', class: "btn btn-primary" %>
						    </div>
						  <%end%>
						</div>
		  		</div>
		  	<%end%>
		  </div>
		<%else%>
			<div class="well">
	  		<a href="#modalInventory" role="button" data-toggle="modal">Cree su primer inventario.</a>
	  	</div>
		<%end%>
	</div>
</fieldset>
<div id="forms">
	<%=render "form"%>
</div>

app/views/inventories/show.html.erb
<%= title "#{@inventory.site} -  Stocktaking" %>
<fieldset>
	<div class="accordion" id="accordion1">
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseOne">
          Inventario "<%=@inventory.site %>"
        </a>
      </div>
      <div id="collapseOne" class="accordion-body collapse in">
        <div class="accordion-inner">
          <strong> Descripción: </strong>
          <p><%=@inventory.details %></p>
          <p><strong> Finalizado: </strong><%= @inventory.finished ? "Sí" : "No" %></p>
  				<% if @inventory.finished == false%>
            <a href="#modalInventory" role="button" class="btn btn-mini" data-toggle="modal"><i class="icon-edit" rel= "tooltip" title= "Editar Inventario"></i></a>
    				<%=link_to(content_tag(:span, content_tag(:i, nil, :class => "icon-trash")), inventory_path(@inventory), method: :delete, data:{confirm: "¿Realmente deseas elminiar este inventario?"}, class: "btn btn-mini", :rel => "tooltip", :"title" => "Eliminar Inventario")%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
	<% if @inventory.finished == false%>
    <legend>Elementos <a href="#modalElement" role="button" class="btn btn-mini btn-success" data-toggle="modal"><i class="icon-plus-sign" rel= "tooltip" title= "Nuevo Elemento"></i></a> </legend>
  <%else%>
    <legend>Elementos</legend>
  <%end%>
	<div id="elements">
	  <% if @inventory.elements.count >= 1%>
			<table class="table table-hover table-bordered">
		    <thead>
		      <tr>
		        <th>Nombre</th>
		        <th>Referencia</th>
		        <th>Estado</th>
		        <th>Valor</th>
		        <th>Detalles</th>
		        <th>Acciones</th>
		      </tr>
		    </thead>
			<%=render @elements.order("loaned desc")%>
      </table>
      <%= paginate @elements%>
	  <%else%>
	  	<div class="well">
	  		<a href="#modalElement" role="button" data-toggle="modal">Cree el primer elemento para este inventario.</a>
	  	</div>
	  <%end%>
	</div>
</fieldset>
<div id="forms">
	<%=render "form"%>
	<%=render "elements/form"%>
</div>
<div >
  <hr class="special_hr" >
  <%=link_to "Todos los inventarios", inventories_path, class: "btn btn-primary btn-large"%>
  <% if @inventory.finished == false%>
  <%=link_to "Finalizar Inventario", finish_inventory_path(@inventory), data:{confirm: "¿Realmente deseas finalizar la edición de este inventario?"}, class: "btn btn-success btn-large", method: :put, id: 'finished_inventory'%>
  <%else%>
    <%=link_to "Inventario Finalizado", "#", class: "btn btn-info btn-large", id: 'info_finished_inventory'%>
  <%end%>
</div>

app/views/inventories/update.js.erb
<% unless @inventory.finished? %>
  <% if @inventory.errors.messages.blank? %>
    <% if $path == "/inventories" %>
  		location.href = '<%inventories_path %>'
  	<% else %>
  	  location.href = '<%inventory_path(@inventory)%>'
  	<% end %>
  <% else %>
    <%
    error = '<ul>'
    @inventory.errors.messages.each do |msg|
      error += "<li>#{I18n.t(msg[0])} #{msg[1].first}</li>"
    end
    error += "</ul>"
    %>
    $('div#errors_edit_<%=@inventory.id%>').html('<%= error.html_safe %>').show();
  <% end %>
<% else %>
  location.href = '<%inventory_path(@inventory) %>'
<% end %>