config/routes.rb
Stocktaking::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :inventories, only: [:create, :destroy, :update, :index, :show] do
    resources :elements, only: [:create, :destroy, :update, :show] do
      resources :loans, only: [:create, :update]
    end
  end

  get "loans/loaned_elements_to_me", to: "loans#loaned_elements_to_me", as: :loaned_elements_to_me
  get "loans/loaned_elements_by_me", to: "loans#loaned_elements_by_me", as: :loaned_elements_by_me

  put "inventories/:id/finish_inventory", to: "inventories#finish_inventory", as: :finish_inventory

  put "loans/:id/finish_loan", to: "loans#finish_loan", as: :finish_loan

  root :to => "home#index"

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :element
  belongs_to :user
  belongs_to :loaned_to, :class_name => 'User'
  attr_accessible :loaned_to_id, :user_id, :element_id, :start_date, :end_date, :finished

  validates_presence_of :user, :loaned_to, :start_date, :element

  scope :finished, where(["finished = ?", true])
  scope :unfinished, where(["finished = ?", false])

end

app/controllers/loans_controller.rb
# encoding: utf-8
class LoansController < ApplicationController
  require 'action_view'
  include ActionView::Helpers::DateHelper
  before_filter :authenticate_user!
  before_filter :get_element, :except => [:finish_loan, :loaned_elements_to_me, :loaned_elements_by_me]

  def get_element
    @element = Element.find(params[:element_id])
  end

  def loaned_elements_by_me
    #@loaned_elements_by_me: elements that I have been loaned to other users.
    @loans = current_user.loans.page(params[:page]).per(10).order(:finished)
  end

  def loaned_elements_to_me
    #@loaned_elements_to_me elements that other users loaned to me.
    @loans = Loan.where(:loaned_to_id => current_user).page(params[:page]).per(10).order(:finished)
  end

  def create
    unless @element.loaned
      @loan = @element.loans.build(params[:loan])
      @loan.element = @element
      @loan.user = @element.inventory.user
      respond_to do |format|
        if @loan.save
          if @element.update_attribute(:loaned, true)
            flash[:notice] = "Usted ha prestado el elemento #{@element.name.camelcase} a #{@loan.loaned_to.full_name.camelcase}."
          else
            flash[:alert] = "El elemento no se pudo prestar."
          end
        else
          flash[:alert] = "El elemento no se pudo prestar, falta algún atributo para el préstamo?."
        end
        format.js
      end
    else
      flash[:alert] = "El elemento ya ha sido prestado."
    end
  end

  def update
    @loan = Loan.find(params[:id])
    unless @loan.finished
      respond_to do |format|
        if @loan.update_attributes(params[:loan])
          flash[:notice] = "El préstamo se ha actualizado."
        else
          flash[:alert] = "El préstamo no pudo ser actualizado."
        end
        format.js
      end
    else
      flash[:alert] = "No se puede actualizar un préstamo que ya ha finalizado."
    end
  end

  def finish_loan
    @loan = Loan.find(params[:id])
    @element = @loan.element
    if @element.loaned
      if @loan.update_attributes(finished: true, end_date: Time.now)
        if @element.update_attribute(:loaned, false)
          flash[:notice] = "El préstamo ha finalizado, la duración del préstamo fue de #{distance_of_time_in_words(@loan.start_date, @loan.end_date)}."
          redirect_to params[:return]
        else
          flash[:alert] = "No se pudo actualizar el elemento."
          redirect_to params[:return]
        end
      else
        flash[:alert] = "No se pudo finalizar el préstamo del elemento."
        redirect_to params[:return]
      end
    else
      flash[:alert] = "No se pudo finalizar el préstamo del elemento."
      redirect_to params[:return]
    end
  end
end

app/views/loans/_loan.html.erb
<div class="loans">
	<legend>Historial de péstamos</legend>
	<div id="loans">
		<%if @loans.size == 0%>
			<div class="well">
	  		<a href="#modalLoan<%="#{@element.id}"%>" role="button" data-toggle="modal">Este elemento nunca ha sido prestado, realice el primer préstamo de este elemento.</a>
	  	</div>
		<%else%>
			<table class="table table-hover table-bordered">
		    <thead>
		      <tr>
		        <th>ID</th>
		        <th>Prestado a</th>
		        <th>Fecha de inicio</th>
		        <th>Finalizado?</th>
		        <th>Fecha de finalización</th>
		        <th>Duración del préstamo</th>
		        <th>Editar</th>
		      </tr>
		    </thead>
		    <% @loans.each do |loan|%>
					<tbody>
						<% unless loan.finished%>
					    <tr class= "loaned">
					  <%else%>
					    <tr>
					  <%end%>
						<td><%= loan.id %></td>
						<td><%= loan.loaned_to.full_name %></td>
						<td><%= l loan.start_date, :format => :special %></td>
						<td><%= loan.finished ? "Sí" : "No"%></td>
						<% if loan.finished %>
							<td><%= l loan.end_date.localtime, :format => :special %></td>
							<td><%= distance_of_time_in_words(loan.start_date, loan.end_date)%></td>
							<td>N/A</td>
						<%else%>
							<td>N/A</td>
							<td>N/A</td>
							<td>
								<a href="#modalEdit<%="#{loan.id}"%>" role="button" class="btn btn-mini" data-toggle="modal"><i class="icon-edit" rel= "tooltip" title= "Editar Préstamo"></i></a>
							</td>
						<%end%>
						<!--Modal edit-->
						<div id="modalEdit<%="#{loan.id}"%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalEditLabel" aria-hidden="true">
						  <div class="modal-header" style="height: 44px;">
						    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						    <h3 id="modalEditLabel">Editar Préstamo</h3>
						    <hr>
						  </div>
						  <div id="errors_edit_loan_<%=loan.id%>" class="hide errors" style = "float: right"></div>
						  <%=form_for([@inventory, @element, loan], remote: :true, html: {style: "margin-bottom: 0px"}) do |f|%>
					      <div class="modal-body">
					        <%= f.label :loaned_to_id , "*Prestar a"%>
					        <%= f.select :loaned_to_id , options_for_select(User.all_users(current_user))%>
					        <%= f.label :start_date , "*Fecha de inicio"%>
					        <%= f.text_field :start_date, id: 'datetimepicker'%>
					        <%= hidden_field_tag :return, "#{inventory_element_path(@element.inventory, @element)}"%>
					      </div>
					      <div class="modal-footer">
					        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
					        <%= f.submit 'Aceptar', class: "btn btn-primary" %>
					      </div>
					    <%end%>
						</div>
					</tbody>
				<%end%>
  		</table>
		<%end%>
	</div>
</div>

app/views/loans/create.js.erb
<% unless @element.loaned %>
  <% if @loan.errors.messages.blank? %>
    location.href = '<% params[:return] %>'
  <% else %>
    <%
    error = '<ul>'
    @loan.errors.messages.each do |msg|
      error += "<li>#{I18n.t(msg[0])} #{msg[1].first}</li>"
    end
    error += "</ul>"
    %>
    $('div#errors_loan_element_<%=@element.id%>').html('<%= error.html_safe %>').show();
  <% end %>
<% else %>
  location.href = '<% params[:return] %>'
<% end %>

app/views/loans/loaned_elements_by_me.html.erb
<%= title "Elementos que he prestado -  Stocktaking" %>
<fieldset>
  <div class="my_loans">
    <legend>Préstamos realizados por mi</legend>
    <%if @loans.size > 0 %>
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>Elemento</th>
            <th>Prestado a</th>
            <th>Fecha de inicio</th>
            <th>Finalizado?</th>
            <th>Fecha de finalización</th>
            <th>Duración del préstamo</th>
            <th>Editar</th>
          </tr>
        </thead>
        <% @loans.each do |loan|%>
          <tbody>
            <% unless loan.finished%>
              <tr class= "loaned">
            <%else%>
              <tr>
            <%end%>
            <td><%= link_to loan.element.name, inventory_element_path(loan.element.inventory, loan.element)%></td>
            <td><%= loan.loaned_to.full_name %></td>
            <td><%= l loan.start_date.localtime, :format => :special %></td>
            <td><%= loan.finished ? "Sí" : "No"%></td>
            <% if loan.finished %>
              <td><%= l loan.end_date.localtime, :format => :special %></td>
              <td><%= distance_of_time_in_words(loan.start_date, loan.end_date)%></td>
              <td>N/A</td>
            <%else%>
              <td>N/A</td>
              <td>N/A</td>
              <td>
                <div class="btn-group">
                  <a href="#modalEdit<%="#{loan.id}"%>" role="button" class="btn btn-small" data-toggle="modal"><i class="icon-edit" rel= "tooltip" title= "Editar Préstamo"></i></a>
                  <%=link_to(content_tag(:span, content_tag(:i, nil, :class => "icon-remove")), finish_loan_path(loan)+"?return=#{loaned_elements_by_me_path}", method: :put, data:{confirm: "¿Realmente desea finalizar el préstamo de este elemento?"}, class: "btn btn-small btn-success", :rel => "tooltip", :"title" => "Finalizar Préstamo del elemento")%>
                </div>
              </td>
            <%end%>
            <!--Modal edit-->
            <div id="modalEdit<%="#{loan.id}"%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalEditLabel" aria-hidden="true">
              <div class="modal-header" style="height: 44px;">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="modalEditLabel">Editar Préstamo</h3>
                <hr>
              </div>
              <div id="errors_edit_loan_<%=loan.id%>" class="hide errors" style = "float: right"></div>
             <%=form_for([loan.element.inventory, loan.element, loan], remote: :true, html: {style: "margin-bottom: 0px"}) do |f|%>
                  <div class="modal-body">
                    <%= f.label :loaned_to_id , "*Prestar a"%>
                    <%= f.select :loaned_to_id , options_for_select(User.all_users(current_user))%>
                    <%= f.label :start_date , "*Fecha de inicio"%>
                    <%= f.text_field :start_date, id: 'datetimepicker'%>
                    <%= hidden_field_tag :return, "#{loaned_elements_by_me_path}"%>
                  </div>
                  <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <%= f.submit 'Aceptar', class: "btn btn-primary" %>
                  </div>
                <%end%>
            </div>
          </tbody>
        <%end%>
      </table>
      <%= paginate @loans%>
    <%else%>
      <div class="well">
        <%=link_to "Seleccione un elemento de sus inventarios y empiece a prestar.", inventories_path%>
      </div>
    <%end%>
  </div>
</fieldset>

app/views/loans/loaned_elements_to_me.html.erb
<%= title "Elementos que me han prestado -  Stocktaking" %>
<fieldset>
  <div class="loans_to_me">
    <legend>Préstamos que me han hecho</legend>
    <%if @loans.size > 0 %>
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>Elemento</th>
            <th>Prestado por</th>
            <th>Fecha de inicio</th>
            <th>Finalizado?</th>
            <th>Fecha de finalización</th>
            <th>Duración del préstamo</th>
          </tr>
        </thead>
        <% @loans.each do |loan|%>
          <tbody>
            <% unless loan.finished%>
              <tr class= "loaned">
            <%else%>
              <tr>
            <%end%>
            <td><%= link_to loan.element.name, inventory_element_path(loan.element.inventory, loan.element)%></td>
            <td><%= loan.user.full_name %></td>
            <td><%= l loan.start_date.localtime, :format => :special %></td>
            <td><%= loan.finished ? "Sí" : "No"%></td>
            <% if loan.finished %>
              <td><%= l loan.end_date.localtime, :format => :special %></td>
              <td><%= distance_of_time_in_words(loan.start_date, loan.end_date)%></td>
            <%else%>
              <td>N/A</td>
              <td>N/A</td>
            <%end%>
            <!--Modal edit-->
            <div id="modalEdit<%="#{loan.id}"%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalEditLabel" aria-hidden="true">
              <div class="modal-header" style="height: 44px;">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="modalEditLabel">Editar Préstamo</h3>
                <hr>
              </div>
              <div id="errors_edit_loan_<%=loan.id%>" class="hide errors" style = "float: right"></div>
              <%=simple_form_for([loan.element.inventory, loan.element, loan], remote: :true, html: {style: "margin-bottom: 0px"}) do |f|%>
                <div class="modal-body">
                  <%= f.input :loaned_to_id , label: "Prestar a:", collection: User.all_users(current_user) %>
                  <%= f.input :start_date, label: "Fecha de inicio" %>
                </div>
                <div class="modal-footer">
                  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                  <%= f.button :submit , 'Aceptar', class: "btn btn-primary" %>
                </div>
              <%end%>
            </div>
          </tbody>
        <%end%>
      </table>
      <%= paginate @loans%>
    <%else%>
      <div class="well">
        <p>Aún no te han prestado nada.</p> 
      </div>
    <%end%>
  </div>
</fieldset>

app/views/loans/update.js.erb
<% unless @loan.finished? %>
  <% if @loan.errors.messages.blank? %>
  	location.href = '<% params[:return] %>'
  <% else %>
    <%
    error = '<ul>'
    @inventory.errors.messages.each do |msg|
      error += "<li>#{I18n.t(msg[0])} #{msg[1].first}</li>"
    end
    error += "</ul>"
    %>
    $('div#errors_loan_element_<%=@element.id%>').html('<%= error.html_safe %>').show();
  <% end %>
<% else %>
  location.href = '<% params[:return] %>'
<% end %>