config/routes.rb
Stocktaking::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :inventories, only: [:create, :destroy, :update, :index, :show] do
    resources :elements, only: [:create, :destroy, :update, :show] do
      resources :loans, only: [:create, :update]
    end
  end

  get "loans/loaned_elements_to_me", to: "loans#loaned_elements_to_me", as: :loaned_elements_to_me
  get "loans/loaned_elements_by_me", to: "loans#loaned_elements_by_me", as: :loaned_elements_by_me

  put "inventories/:id/finish_inventory", to: "inventories#finish_inventory", as: :finish_inventory

  put "loans/:id/finish_loan", to: "loans#finish_loan", as: :finish_loan

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="contaniner">
    <%if notice%>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <p class="notice"><%= notice %></p>
      </div>
    <%end%>
    <%if alert%>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <p><%= alert %></p>
      </div>
    <%end%>
  </div>

  <div class="container-narrow">
    <div class="masthead">
      <ul class="nav nav-pills pull-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" id="drop5" role="button" data-toggle="dropdown" href="<%=inventories_path%>">Inventarios<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%=link_to(content_tag(:span, content_tag(:i, nil, :class => "icon-star")+" Todos"), inventories_path)%></li>
                  <%inventories = Inventory.where(user_id: current_user)%>
                  <%inventories.each do |inventory|%>
                    <li><%=link_to(content_tag(:span, content_tag(:i, nil, :class => "icon-chevron-right")+"  #{inventory.site}"), inventory_path(inventory))%></li>
                  <%end%>
                </ul>
            </li>

            <li class="dropdown">
              <a class="dropdown-toggle" id="drop5" role="button" data-toggle="dropdown" href="#">Préstamos<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%=link_to(content_tag(:span, content_tag(:i, nil, :class => "icon-hand-left")+" Yo he prestado"), loaned_elements_by_me_path)%></li>
                  <li><%=link_to(content_tag(:span, content_tag(:i, nil, :class => "icon-hand-right")+" Me han prestado"), loaned_elements_to_me_path)%></li>
                </ul>
            </li>
          <li class="dropdown">
            <a class="dropdown-toggle" id="drop5" role="button" data-toggle="dropdown" href="#"><%=current_user.full_name%><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%=link_to(content_tag(:span, content_tag(:i, nil, :class => "icon-user")+" Editar Cuenta"), edit_user_registration_path(current_user))%></li>
                <li><%=link_to(content_tag(:span, content_tag(:i, nil, :class => "icon-off")+" Salir"), destroy_user_session_path,  method: :delete)%></li>
              </ul>
          </li>
          <li><%= image_tag current_user.photo.url(:tiny), class: "img-rounded"%></li>
        <% else %>
          <li><%=link_to "Iniciar Sesión", new_user_session_path%></li>
        <% end %>
      </ul>
      <h3><%=link_to "Stocktaking", root_path, class: "active"%></h3>
    </div>
    <hr>
  </div>

  <div id="yield" class="container">
    <%= yield %>
  </div>

  <footer class="footer">
    <div class="container">
      <p><a href="http://sancarborromeo.jimdo.com" target="_blank">Colegio Técnico Industrial San Carlos Borromeo </a></p>
      <p>
      <p>Designed and built by <a href="https://plus.google.com/u/1/108981190606310585411/posts" target="_blank">Hernán Orozco</a></p>
      <p>
    </div>
  </footer>
</body>
</html>